$(function(){
    //所有频道点击
    $(".channel-mine-btn").click(function(){
        window.location.href="channel-mine.html";
    });
    //tab导航栏点击
    $("body").on("click",".channel-tab>div",function(){
        $(".channel-tab>div").removeClass("channel-tab-act").children(".channel-tab-line").addClass("out");
        $(this).addClass("channel-tab-act").children(".channel-tab-line").removeClass("out");
    });
    //频道搜索点击
    $(".channel-search-input").click(function(){
        window.location.href="channel-search.html";
    });
    //税种筛选按钮点击
    $(".channel-tax-sel-btn").click(function(){
        if($(".channel-tax-sel-model").hasClass("out")){
            $(".channel-tax-sel-model").removeClass("out");
        }else{
            $(".channel-tax-sel-model").addClass("out");
        }
    });
    //税种列表点击
    $("body").on("click",".channel-c-main-list>div",function(){
        $(".channel-c-main-list>div").removeClass("channel-list-act");
        $(this).addClass("channel-list-act");
        $(".channel-sz-show").html($(this).html().length>4?$(this).html().slice(0,4)+"..":$(this).html());
        $(".channel-sz-hidden").html($(this).html());
        $(".channel-tax-sel-model").addClass("out");
    });
    //开通会员卡点击
    $(".kt-channelvip-btn").click(function(){
        window.location.href="channel-vip-card.html";
    });
    //频道列表点击
    $("body").on("click",".channel-page-li",function(){
        window.location.href="channel-detail.html";
    });
});